// Generated by Wrangler by running `wrangler types`
// Extended for auth and whitelist management

interface Env {
	AUTH_KV: KVNamespace;
	/** PDF uploads and job state JSON for validation pipeline */
	VALIDATION_R2: R2Bucket;
	/**
	 * Runs validation out-of-band: `waitUntil` only lasts ~30s after POST /api/validate returns,
	 * so production uses this queue (consumer has long wall time). Omit binding only for local
	 * fallbacks that use `ctx.waitUntil` instead.
	 */
	VALIDATION_QUEUE?: Queue<{ jobId: string }>;
	/** OpenAI API key for protocol vs lab manual extraction and comparison */
	OPENAI_API_KEY?: string;
	/** Model for extraction (default gpt-4o-mini) */
	OPENAI_MODEL?: string;
	/** Model for PDF→text via Responses API (default gpt-4o; needs vision / PDF support) */
	OPENAI_PDF_MODEL?: string;
	/** Max output tokens for PDF text extraction (string number; default 16384) */
	OPENAI_PDF_MAX_OUTPUT_TOKENS?: string;
	/** Set "false" to use synchronous Responses (may time out on large PDFs). Default: background + poll. */
	OPENAI_PDF_RESPONSES_BACKGROUND?: string;
	/** Max time to poll background response, ms (string number; default 1500000 ≈ 25m) */
	OPENAI_PDF_POLL_MAX_MS?: string;
	/** If "true", continue the pipeline when PDF extraction is shorter than the heuristic minimum (low quality). */
	OPENAI_PDF_ALLOW_SHORT?: string;
	/**
	 * Ms to wait between protocol and lab PDF extraction (gpt-4o TPM). Max 600000.
	 * Omit for default 55000. Set "0" to disable (faster but more 429 risk on low TPM).
	 */
	OPENAI_PDF_EXTRACT_STAGGER_MS?: string;
	/**
	 * PDF TPM safety: small first Responses request + pause before follow-ups (default on).
	 * Set "false" if your gpt-4o TPM limit is high and you want fewer delays.
	 */
	OPENAI_PDF_LOW_TPM?: string;
	/** With LOW_TPM: max_output_tokens for the first PDF extract only (default 8192). */
	OPENAI_PDF_LOW_TPM_FIRST_MAX?: string;
	/** With LOW_TPM: ms to wait before 2nd+ PDF Responses calls (default 70000). */
	OPENAI_PDF_LOW_TPM_GAP_MS?: string;
	/** Optional cap on first PDF pass max_output_tokens only (no pauses). Use with tight TPM. */
	OPENAI_PDF_INITIAL_MAX_OUTPUT?: string;
	/** Optional cap on every PDF Responses max_output_tokens (applies to all passes). */
	OPENAI_PDF_MAX_OUTPUT_REQUEST_CAP?: string;
	/** Fallback: comma-separated emails when KV whitelist is empty */
	EMAIL_WHITELIST?: string;
	/** Resend API key for sending magic link emails */
	RESEND_API_KEY: string;
	/** From address for magic link emails (e.g. noreply@yourdomain.com). Required for production. */
	MAGIC_LINK_FROM?: string;
	/** Base URL of the app for magic links */
	APP_URL: string;
	/** Secret for admin API (X-Admin-Secret header). Required for /api/admin/whitelist */
	ADMIN_SECRET?: string;
}
